name: AestheticMenu
version: '${project.version}'
main: ru.rivendell.aestheticmenu.AestheticMenu
authors:
  - systemdev_
api-version: '1.20'
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true