name: AestheticMenu
version: '${project.version}'
main: ru.rivendell.aestheticmenu.AestheticMenu
api-version: '1.20'
commands:
  aestheticmenu-forceopen:
    aliases:
      - amenu-forceopen
      - am-fe
    usage: /aestheticmenu-forceopen
  aestheticmenu-reload:
    aliases:
      - amenu-reload
      - am-reload
    usage: /aestheticmenu-reload